#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=0:30:00
#PBS -N app-myelin-mapping
#PBS -l vmem=20gb
#PBS -V

set -e

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "computing t1 t2 ratio"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2b ./compute-myelin-map.sh

